oc_louvre_homepage:
    path:     /
    defaults:
        _controller: OCLouvreBundle:Louvre:index

oc_louvre_billetterie:
    path:     /billetterie
    defaults:
        _controller: OCLouvreBundle:AchatBilletLouvre:achatBillets

oc_louvre_detaille:
    path:     /detaille/{id}/{produit}
    defaults:
        _controller: OCLouvreBundle:DetailleBilletLouvre:detailleBillets
    requirements:
        id: \d+

oc_louvre_enregistrer:
    path:     /billetterie/enregistrer
    defaults:
        _controller: OCLouvreBundle:Louvre:enregistrerBillets

oc_louvre_jour_ferier:
    path:     /count-visitors/{dateChoisie}
    defaults:
        _controller: OCLouvreBundle:Louvre:countVisitors

oc_louvre_prix:
    path:     /prix/{dateNaissance}/{dateVisite}/{idProduit}
    defaults:
        _controller: OCLouvreBundle:Louvre:prix

