services:
#    oc_louvre.example:
#        class: OC\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_louvre.datesNassances:
        class: OC\LouvreBundle\Services\DateNaissance

    oc_louvre.tarifs:
        class: OC\LouvreBundle\Services\Tarif

    oc_louvre.importTarif:
        class: OC\LouvreBundle\Services\ImportTarif
        arguments:
            - "@oc_louvre.tarifs"
            - "@doctrine.orm.entity_manager"

    oc_louvre.generateurNumeroBillet:
        class: OC\LouvreBundle\Services\GenerateurNumeroBillet
        arguments:
            - "@doctrine.orm.entity_manager"
