services:
#    oc_louvre.example:
#        class: OC\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_louvre.datesNassances:
        class: OC\LouvreBundle\Services\DateNaissance

    oc_louvre.tarifs:
        class: OC\LouvreBundle\Services\Tarif
