<?php

namespace OC\LouvreBundle\Repository;
use Doctrine\DBAL\Driver\PDOException;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * BilletsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletsRepository extends \Doctrine\ORM\EntityRepository
{
    public function recupDernierBilletAjouter() {

        //$query = $this->_em->createQuery('SELECT t FROM OCLouvreBundle:Billets t ORDER BY t.id DESC ');
        //$query = $this->_em->createQuery('SELECT t FROM OCLouvreBundle:Billets t');


        $query = $this->_em->createQuery('SELECT t FROM OCLouvreBundle:Billets t ORDER BY t.id DESC ');
        $dernierBillets = $query->setMaxResults(1)->getOneOrNullResult();


        //$dernierBillets = $query->getOneOrNullResult();




    }
}
