<?php

namespace OC\LouvreBundle\Repository;

/**
 * JoursFermetureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoursFermetureRepository extends \Doctrine\ORM\EntityRepository
{
}
