<?php

namespace OC\LouvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarifProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifProduitRepository extends EntityRepository
{
    public function recuperePrix($tarifs, $produits) {

    }
}
