<?php

namespace OC\LouvreBundle\Repository;

/**
 * TarifProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
