<?php

namespace OC\LouvreBundle\Repository;

/**
 * TarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class TarifsRepository extends EntityRepository
{
    public function findListTarifs($tarif) {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->where('t.localisateurTarif=:localisateur_tarif')
            ->setParameter('localisateur_tarif', $tarif);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findTarif($tarifId) {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->where('t.id=:id')
            ->setParameter('id', $tarifId);

        return $qb
            ->getQuery()
            ->getResult();
    }

}
