<?php

namespace OC\LouvreBundle\Repository;

/**
 * TarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class TarifsRepository extends EntityRepository
{
    public function findTarifs($tarifs) {
        $repository =  $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('OCLouvreBundle:Tarifs');

        $listTarifs = $repository->findBy($tarifs);

        return $listTarifs;
    }
}
