<?php

namespace OC\LouvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarifProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifProduitRepository extends EntityRepository
{
    public function findPrix(array $idTarifs, $idProduits) {
        foreach ($idTarifs as $key => $value){
            $qb = $this->createQueryBuilder('tp');
            $qb
                ->where('tp.tarif=:idTarif')
                    ->setParameter('idTarif', $value)
                ->andWhere('tp.produit=:idProduit')
                    ->setParameter('idProduit', $idProduits);

            $result = $qb->getQuery()->getResult();
            foreach ($result as $key => $value) {
                $prixUnitaire[] = (float)$value->getPrixUnitaire();
            }
        }
        return $prixUnitaire;
    }
}
