<?php

namespace OC\LouvreBundle\Repository;

/**
 * TarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class TarifsRepository extends EntityRepository
{
    public function findListTarifs($tarif) {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->where('t.localisateurTarif=:localisateur_tarif')
            ->setParameter('localisateur_tarif', $tarif);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function recupDernierBilletAjouter() {
        // Verification sil existe des Billets
        $query = $this->_em->createQuery('SELECT 1 FROM OCLouvreBundle:Tarifs');
        $dernierBillets = $query->execute();

        // Si il existe des billets en recupére le dernier et en le renvoi
        if (!empty($dernierBillets)){
            $query = $this->_em->createQuery('SELECT t FROM OCLouvreBundle:Tarifs t ORDER BY t.id DESC ');
            $dernierBillets = $query->setMaxResults(1)->getOneOrNullResult();
        }
        return $dernierBillets;

    }
}
