acme_louvre_homepage:
    path:     /
    defaults: { _controller: AcmeLouvreBundle:Louvre:index }

acme_louvre_billetterie:
    path:     /billetterie
    defaults: { _controller: AcmeLouvreBundle:Louvre:achatBillet }

acme_louvre_detaille:
    path:     /detaille
    defaults: { _controller: AcmeLouvreBundle:Louvre:detalleBillet }
